name: py
    
on:
 repository_dispatch:
 workflow_dispatch:
# schedule:
#    - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: first

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10 #install the python needed
      - name: execute py script # run the run.py to get the latest data
        run: |
            sudo apt-get install -y ffmpeg
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            python app.py

        env:
          ASSEMBLYAI_API_KEY: ${{ secrets.ASSEMBLYAI_API_KEY }}
